remote_theme: dieghernan/chulapa
repository: dadosdelaplace/dadosdelaplace.github.io
url: https://dadosdelaplace.github.io
favicon: ./assets/img/site/favicon.ico
baseurl: ""

# Find errors on this file with http://www.yamllint.com/
# Chulapa docs: https://dieghernan.github.io/chulapa/docs/02-config

# A. Site Settings /SEO options
# Overall options for your site, would affect your site SEO

# Site settings
locale                  : #default["en-US"] format language-TERRITORY , e.g fr, en-GB, es-MX, pt-BR
title                   : Javier Álvarez Liébana
title_separator         : #default [" | "]
subtitle                : Dados de Laplace
description             : Mathematician, PhD Stats, Assistant Professor and scicomm (Matemático, doctor en estadística, investigador y divulgador científico)
words_per_minute        : #default[200]
timezone                : "Europe/Madrid"

# SEO
og_image                : https://github.com/dadosdelaplace/dadosdelaplace.github.io/blob/master/assets/img/site/banner.jpg
twitter_site            : dadosdelaplace
author:
  name                  :  Javier Álvarez Liébana
  avatar                :  ./assets/img/site/logo_navegador.png
  location              :  "Madrid, Spain"
  links:     
    - url: https://twitter.com/dadosdelaplace
      icon: fab fa-twitter
    - url: https://instagram.com/javieralvarezliebana
      icon: fa fa-instagram
    - url: https://cartasdelaplace.substack.com
      icon: fas fa-envelope
    - url: https://github.com/dadosdelaplace/
      icon: fab fa-github
fa5_kit_code:  # Your FontAwesome 5 kit code. If not provided a free hosted version (slower) will be loaded:  https://fontawesome.com/ 
fa_v4_support: #Bool Add FontAwesome 4 support 
# Web tracking - Google services https://analytics.google.com/analytics/web/
# gtag_id is the preferred option, see https://developers.google.com/analytics/devguides/collection/gtagjs/migration?hl=en
# analytics provided for backwards compatibility
gtag_id                 :  
analytics_id            :  

# Search providers
# Available free search engines:
# - lunr https://lunrjs.com/ 
# - algolia v4 https://www.algolia.com/ - needs further configuration
# - google custom search engine https://cse.google.es/ 
search:
  provider              : lunr #Select a provider for enable search: lunr, algolia, google
  label                 :  #default ["Search"] Text on navbar when search is enabled 
  landing_page          :  #default ["/search"] Link on navbar 
  lunr_maxwords         :  #default [30] lunr only - May slow down your site build
  algolia_logo          :  true #Displays algolia logo. Should be set to true if you are on a community plan, otherwise false.  

google_cse_id: #Your cse id
# This site uses jekyll-algolia plugin https://community.algolia.com/jekyll-algolia/
# Recommended additional configuration provided, could be modified. Add your own parameters
algolia:                                                                   
  application_id        : 
  index_name            : 
  search_only_api_key   : 
  files_to_exclude:         #Optional
    - _layouts/*.html
    - _includes/*.html
  extensions_to_index:      #Optional
    - html
    - md
  searchableAttributes:     #Optional                                                    
    - title                                                                    
    - headings                                                                 
    - unordered(content)                                                       
    - unordered(subtitle)                                                      
    - unordered(categories)                                                    
    - unordered(collection)                                                    
    - unordered(tags) 
  customRanking:            #Optional
    - desc(include_on_search)
    - desc(title)
    - desc(content) 
    - desc(subtitle)
    
comments:
  provider:         #Enable comments via Disqus https://disqus.com/
  disqus_shortname: #Your site id : check your address https://{{ disqus.shortname }}.disqus.com/admin/
  
# B. Navigation
# Configure your navbar and the footer of your site

# Navbar: 
#   "brand" options would be set on the left side of your navbar
#   "nav" would be set on the right side. Two-level nav links available
# B. Navigation
navbar:
  style     : dual # default is the classical top navbar, set "fab" for a floating action button navbar or "dual"
  expand    : xl # At which device size expand the navbar menu. default[md] https://getbootstrap.com/docs/4.5/layout/overview/
  brand:
    title   : Javier Álvarez Liébana<br>Dados de Laplace # Title in navbar
    url     :  # default["url/baseurl"]
    img     :  # https://dadosdelaplace.github.io/assets/img/site/logo_navegador.png
  nav:
  - title   : About me # Label
    child   :
      - title   : About me
        url     : /about
      - title   : Media
        url     : /media
  - title   : CV
    url     : /cv
  - title   : Blog
    child   :
      - title : '<i class="fab fa-r-project" aria-hidden="true"></i> Learning R (aprendiendo R)'
        url   : /tags
      - title : Stats (estadística)
        url   : /categories
  - title   : Courses (cursos)
    url     : /courses
  - title   : Teaching (docencia)
    url     : /teaching
  - title   : '<i class="fas fa-envelope" aria-hidden="true"></i> Newsletter'
    url     : https://cartasdelaplace.substack.com
  - title   : '<i class="fab fa-github" aria-hidden="true"></i> Github'
    url     : https://github.com/dadosdelaplace/dadosdelaplace.github.io
  - title   : Social (redes)
    child   :		
     - title   : '<i class="fa fa-twitter" aria-hidden="true"></i> Twitter'
       url     : https://twitter.com/dadosdelaplace
     - title   : '<i class="fa fa-instagram" aria-hidden="true"></i> Instagram'
       url     : https://instagram.com/javieralvarezliebana
     - title   : '<i class="fa fa-spotify" aria-hidden="true"></i> Spotify'
       url     : https://open.spotify.com/playlist/7aIqHopSvoJ4JsFXzNttZH?si=791ed1d8648a440e
# Social links to be placed on your site footer
footer:
  links:
    - label: "RSS"
      icon: "fa fa-rss"
      url:  "./atom.xml"
    - label: "Github"
      icon: "fab fa-github"
      url: "https://github.com/dadosdelaplace"
    - label: "Newsletter"
      icon: "fas fa-envelope"
      url: "https://cartasdelaplace.substack.com"
  copyright: # default is © <year> <name> 
  
# C. Theme Settings
# Google Fonts https://fonts.google.com/, add as many as you need
googlefonts:
 - url : "https://fonts.googleapis.com/css?family=Voltaire:200,300,400,700"
 - url : "https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"

# Theme and colors
chulapa-skin: 
  highlight     :  perldoc
  skin          :  chulapa
  autothemer    :  #true # Bool: Use autotheming
  vars  :
    primary: "#2F414A" # azul oscuro
    secondary: "#F47B53" # naranja-rojo
    success: "#93D8B0" # "#3d7e58" # ahora verde. antes morado --> "#420084" 
    danger: "#EC7383" # "#e15d6f" # "#dc4462" # rojo. antes --> "#f2460d"
    info: "#3a81b9" # azul. antes --> "#7ebcfa"
    warning: "#ff9933" # naranja
    light: "#fefcfb" # blanco/claro. antes --> "eef0f2"
    dark: "#182830" # "#30414a" color de navbar. antes --> "#000633"
    headings-font-family: Voltaire
    enable-responsive-font-sizes: true
    # body-color                  : black
    # primary                     : lightskyblue #default ["#007bff"] - Bootstrap blue
    
# D. Jekyll Defaults and collections: see https://jekyllrb.com/

# Blog pagination: on this site /blog/index.html. https://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: "/blog/page:num/"
paginator_maxnum: 3  
collections_dir     : collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
permalink: /:year:month_:title/
# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
      include_on_search   : false
      cloudtag_url        : /tags #This is where the link on tags would redirect
      cloudcategory_url   : /categories #This is where the link on categories would redirect
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_bottomnavs   : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_author       : true
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Blog
          url: /blog/
  -
    scope:
      path: ""
      type: "cheatsheet"
    values:
      header_type       : "hero"
      show_bottomnavs   : true
      show_sociallinks  : true
      include_on_search : true
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Cheatsheets
          url: /cheatsheets


# XX. Other settings - no need to modify
# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-redirect-from


# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor
  - oldcontent

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style



