---
title: "Strongly consistent autoregressive predictors in abstract Banach spaces"
date: 2019-03-01
author:
  - name: María Dolores Ruiz Medina
    url: https://www.researchgate.net/profile/Maria-Ruiz-Medina
    orcid: 0000-0001-7445-7060
    affiliation: Universidad de Granada
  - name: Javier Álvarez Liébana
    url: https://javieralvarezliebana.github.io/
    orcid: 0000-0003-0671-3856
    affiliation: Universidad Complutense de Madrid
categories: 
  - Banach spaces
  - Consistency
  - Functional data
  - Functional time series
pub-info:
  reference: >-
    <a href="https://www.researchgate.net/profile/Maria-Ruiz-Medina">María Dolores Ruiz Medina</a>, <a href="https://javieralvarezliebana.github.io/">Javier Álvarez Liébana</a>, «Strongly consistent autoregressive predictors in abstract Banach spaces», <em>J. Multivariate Anal.</em> 170, 186-201 (2019), doi: <a href="https://doi.org/10.1016/j.jmva.2018.08.001"><code>10.1016/j.jmva.2018.08.001</code></a>
  links:
    - name: Preprint
      url: 1801.08817.pdf
      icon: fa-solid fa-file-pdf
      local: true
    - name: Versión final
      url: https://www.sciencedirect.com/science/article/pii/S0047259X17307248
      icon: fa-solid fa-scroll
doi: 10.1016/j.jmva.2018.08.001
haiku:
  - Model must align true,
  - Goodness-of-fit shows the way
  - Functional beauty
---

## Materiales

- [Preprint (borrador)](1801.08817.pdf)
- [Artículo (desde sci-hub)](ruiz-medina2018.pdf)
- [Material suplementario](1-s2.0-S0047259X17307248-mmc1.pdf)


## Abstract

This work derives new results on strong consistent estimation and prediction for autoregressive processes of order 1 in a separable Banach space B. The consistency results are obtained for the component-wise estimator of the autocorrelation operator in the norm of the space of bounded linear operators on B. The strong consistency of the associated plug-in predictor then follows in the B-norm. A Gelfand triple is defined through the Hilbert space constructed in Kuelbs' lemma (Kuelbs, 1970). A Hilbert–Schmidt embedding introduces the Reproducing Kernel Hilbert space (RKHS), generated by the autocovariance operator, into the Hilbert space conforming the Rigged Hilbert space structure. This paper extends the work of Bosq (2000) and Labbas and Mourid (2002).

## Código R y datos

El código no fue documentado no está libremente disponible, solo bajo petición

## Cita BibTeX

```bibtex
@article{RuizMedinaAlvarezLiebana19,
  author = {M. D. Ruiz-Medina and J. Álvarez-Liébana},
  title = {Strongly consistent autoregressive predictors in abstract Banach spaces},
  journal = {J. Multivariate Anal.},
  volume = {170},
  pages = {186-201},
  keywords = {Banach spaces, continuous embeddings, functional plug-in predictors, strongly consistent estimators},
  doi = {10.1016/j.jmva.2018.08.001}
  url = {https://www.sciencedirect.com/science/article/pii/S0047259X17307248#sec6},
  year = {2019}
}
```