---
title: "Investigación"
description-meta: "{{< meta website.description >}}"
title-block-banner: "#9E393B"
listing:
  - id: articulos
    contents: "articulos/*/index.qmd"
    sort: "date desc"
    template: ../css/investigacion/listing.ejs
    categories: true
  - id: tesis
    contents: "tesis/*/index.qmd"
    sort: "date desc"
    template: ../css/investigacion/listing.ejs
    categories: true
  - id: software
    contents: "software/*/index.qmd"
    sort: "date desc"
    template: ../css/investigacion/listing.ejs
    categories: true
  - id: capitulos
    contents: "capitulos/*/index.qmd"
    sort: "date desc"
    template: ../css/investigacion/listing.ejs
    categories: true
  - id: congresos
    contents: "congresos/*/index.qmd"
    sort: "date desc"
    template: ../css/investigacion/listing.ejs
    categories: true
page-layout: full
include-back-link: false
toc-location: right
---

En mi corta carrera como investigador desde 2014, mis [**campos de investigación**](https://scholar.google.es/citations?user=Wb3lxFIAAAAJ&hl=es) son o han sido el análisis de [**datos funcionales (FDA)**]{.hl-purple}, metodologías de contraste de bondad de ajuste (goodness-of-fit), predicción de series temporales, implementación de [**Machine Learning aplicado a grafos**]{.hl-purple} y, recientemente, el campo de la bioestadística. Estoy acreditado como [**Contratado Doctor (ANECA)**]{.hl-purple} desde junio de 2022, y acumulo un total de **2 trienios (2014-2020)** y pendiente de solicitar quinquenio de docencia (2014-2019) y sexenio de investigación (hasta 2023 la UCM no lo permitía).

## [Artículos científicos]{.hl-yellow}

:::{#articulos}
:::


## [Software]{.hl-yellow}

:::{#software}
:::


## [Capítulos de libro]{.hl-yellow}

:::{#capitulos}
:::

## [Tesis]{.hl-yellow}

:::{#tesis}
:::

## [Posiciones académicas]{.hl-yellow}

* [**Profesor/investigador Ayudante Doctor en la UCM**]{.hl-purple} en la UCM desde octubre de 2021 hasta la actualidad.

* [**Profesor/investigador Ayudante Doctor en UNIOVI**]{.hl-purple} desde septiembre de 2020 hasta septiembre de 2021.

* [**Profesor/investigador sustituto interio en UNIOVI**]{.hl-purple} desde septiembre de 2018 hasta agosto de 2020.

* [**Investigador contratado FPI en UGR**]{.hl-purple} desde septiembre de 2014 hasta julio de 2018.

## [Estancias]{.hl-yellow}


* [**Estancia postdoctoral**]{.hl-purple} en la Universidad de Santiago de Compostela en enero de 2020 (menos de un mes) con el investigador Wenceslao González Manteiga.

* [**Estancia postdoctoral**]{.hl-purple} en la Universidad de Santiago de Compostela en junio de 2019 (menos de un mes) con el investigador Wenceslao González Manteiga.

* [**Estancia postdoctoral**]{.hl-purple} en el grupo Nanomedicina IDIVAL- UC desde mayo hasta junio de 2019 (1 mes) con el investigador Carlos Renero Lecuna.

* [**Estancia postdoctoral**]{.hl-purple} en la Universidad de Santiago de Compostela desde septiembre hasta octubre de 2018 (1 mes) con el investigador Wenceslao González Manteiga.

* [**Estancia predoctoral**]{.hl-purple} en la Universitè Pierre et Marie Curie (París) desde septiembre de 2017 hasta diciembre de 2017 (3 meses).

* [**Estancia predoctoral**]{.hl-purple} en la Universitè Pierre et Marie Curie (París) desde marzo de 2015 hasta junio de 2015 (3 meses).


## [Transferencia]{.hl-yellow}

* [**Curso de análisis de datos con R en RTVE**]{.hl-purple} para periodistas de marzo a abril de 2023.

* [**Seminario/charla**]{.hl-purple}: «¿Qué hace un matemático como yo en un sitio como este?», organizado por la Universidad de Extremadura. 2022

* [**Curso de visualización de datos**]{.hl-purple} titulado «Analizando datos, visualizando información, contando historias» para la Escuela de Invierno UCM de enero a febrero de 2022.

* [**Entrevista en prensa escrita**]{.hl-red}: [«Las matemáticas detrás del fenómeno Wordle para ganar antes que nadie»](https://www.elconfidencial.com/tecnologia/2022-01-13/matematicas-wordle-juego-estadistica_3357239/). Artículo de Mario Escribano para El Confidencial (13 de enero de 2022).

* [**Divulgación en prensa escrita**]{.hl-red}: [«Los matemáticos también jugamos a la lotería»](https://theconversation.com/los-matematicos-tambien-jugamos-a-la-loteria-aunque-no-deberiamos-174108). Artículo para The Conversation y la Unidad de Cultura Científica de la UCM (20 de diciembre de 2021).

* [**Divulgación en prensa escrita**]{.hl-red}: [«Cómo el ataque de Pearl Harbor cambió la estadística de las pruebas diagnósticas»](https://elpais.com/ciencia/cafe-y-teoremas/2021-12-07/como-el-ataque-de-pearl-harbor-cambio-la-estadistica-de-las-pruebas-diagnosticas.html). Artículo con Joaquín Minaya para El País (7 de diciembre de 2021).

* [**Seminario/charla**]{.hl-purple}: «Ciencia de Datos y COVID-19», organizado por DASCI (Andalucía). Ciclo «Ada Lovelace» 2021

* [**Seminario/charla**]{.hl-purple}: «Mesa redonda: R e COVID», organizado por la asociación Usuarios de Software Libre da Terra de Melide (MeLiSA) (Galicia). 2021

* [**Entrevista en prensa escrita**]{.hl-red}: [«Ni gatos ni pasteles: el anestesista y el matemático que arrasan en redes porque ayudan a entender la pandemia»](https://elpais.com/espana/madrid/2021-08-09/ni-gatos-ni-pasteles-el-anestesista-y-el-matematico-que-arrasan-en-redes-porque-ayudan-a-entender-la-pandemia.html). Artículo de Isabel Valdés para El País (9 de agosto de 2021).

* [**Seminario/charla**]{.hl-purple}: «Estadística en la guerra, tanto en Pearl Harbor como en el desembarco de Normandía» en el XXII ENEM (Murcia), organizado por la ANEM en 2021

* [**Analista y asesor de la Dirección General de Salud Pública de Asturias**]{.hl-green} (mediante artículo 83) de octubre de 2020 a septiembre de 2021. Encargado de la **monitorización y análisis de datos** de la pandemia de COVID-19, y de la creación de un sistema de alertas por concejos, así como su visualización con Shiny.

* [**Seminario/charla**]{.hl-purple}: «A journey through Functional Data Analysis», organizado por el ICMAT (CSIC, Madrid) en 2019

* [**Seminario/charla**]{.hl-purple}: «Machine Learning: supervised and non supervised learning», organizado por IEMATH-GR (Universidad de Granada) en 2016


## [Premios, cargos de gestión y formación]{.hl-yellow}

### [Cargos de gestión]{.hl-purple}

* [**Coordinador del primer semestre de 1º del Grado de Estadística Aplicada**]{.hl-green} de la Facultad de Estudios Estadísticos de la UCM durante el curso académico 2022-2023.


* [**Coordinador del ciclo de conferencias divulgativas**]{.hl-green} de la Facultad de Estudios Estadísticos de la UCM durante el curso académico 2022-2023.

* [**Delegado como enlace con R Hispano**]{.hl-green} (nodo Madrid) por la Facultad de Estudios Estadísticos de la UCM durante los cursos académicos 2021-2022 y 2022-2023.


### [Premios]{.hl-purple}

* [**Contrato Juan de la Cierva**]{.hl-green} - Formación del Ministerio de Ciencia e Innovación.

* [**Seleccionado por la Sociedad Española de Estadística e IO (SEIO)**]{.hl-green} para representarla en «21th European Young Statisticians Meetings» (Belgrado, Serbia) en 2019.

* [**PhD Tesis con honores (Cum Laude) y Mención Internacional**]{.hl-green} en 2018.

* [**Seleccionado por la Sociedad Española de Estadística e IO (SEIO)**]{.hl-green}  para representarla en «Regional workshop European Young Researchs» (París) en 2018.

### [Educación]{.hl-purple}

* [**PhD Tesis (2014 - 2018)**]{.hl-green} por la Universidad de Granada (Granada). Cum Laude y Mención Internacional. Tesis titulada «Inference on linear processes in Hilbert and Banach spaces: statistical analysis of high-dimensional data» bajo la dirección de M. D. Ruiz-Medina. 

* [**Máster en Ingeniería Matemática (2013 - 2014)**]{.hl-green} por la Universidad Complutense (Madrid).

* [**Licenciatura en Matemáticas (2007 - 2013)**]{.hl-green} por la Universidad Complutense (Madrid), especializado en Astronomía y Geodesia. Cursé además un año de Erasmus en Bologna (Italia).  


## [Congresos]{.hl-yellow}

* [**Comité organizador**]{.hl-green}: «4th Spanish Young Statisticians and Operational Researchers Meeting» 2023. Universidad de Santiago de Compostela.

* [**Comité organizador**]{.hl-green}: «3st Spanish Young Statisticians and Operational Researchers Meeting» 2022. Universidad de Elche.

* [**Organizador de mesa redonda**]{.hl-red}: «Mesa redonda: Divulgación de la Estadística y la IO». **Congreso**: XXXIX Congreso Nacional de Estadística e Investigación Operativa (Granada) 2022

* [**Invitado a mesa redonda**]{.hl-red}: «Divulgación en internet y redes sociales». **Congreso**: Congreso Bienal de la Real Sociedad Matemática Española 2022. Universidad de Castilla-La Mancha (Ciudad Real)

* [**Contribución invitada**]{.hl-purple}: «A goodness-of-fit test for functional time series with applications to diffusion processes». **Congreso**: 5th International Symposium on Nonparametric Statistics (ISNPS, Paphos, Chipre) 2022. Autores: J. Álvarez-Liébana, A. López Perez, W. González-Manteiga y M. Febrero-Bande.

* [**Contribución invitada**]{.hl-purple}: «A goodness-of-fit test for functional time series». **Congreso**: XXXIX Congreso Nacional de Estadística e Investigación Operativa (Granada) 2022. Autores: J. Álvarez-Liébana, A. López-Pérez, W. González-Manteiga, M. Febrero-Bande y M. D. Ruiz-Medina.

* [**Contribución invitada**]{.hl-purple}: «A goodness-of-fit test for functional time series with applications to diffusion processes». **Congreso**: New Bridges between Mathematics and Data Science (NBMDS, Valladolid) 2021. Autores: J. Álvarez-Liébana, A. López Perez, W. González-Manteiga y M. Febrero-Bande.

* [**Comité organizador**]{.hl-green}: «III International Workshop on Advances in Functional Data Analysis» 2019. Universdad de Cantabria.

* [**Contribución invitada**]{.hl-purple}: «On the inference of functional time series». **Congreso**: 1st Regional Workshop of European young researchers in statistics (París, Francia) 2018. Autores: J. Álvarez-Liébana.

* [**Contribución invitada**]{.hl-purple}: «Estimación fuertemente consistente de procesos autorregresivos, con variables exógenas, en espacios de Banach abstractos». **Congreso**: XXXVII Congreso Nacional de Estadística e Investigación Operativa (Oviedo) 2018. Autores: J. Álvarez-Liébana y M. D. Ruiz-Medina.

* [**Contribución invitada**]{.hl-purple}: «Strongly-consistent prediction of air pollutants PM10 by high-singular ARBX(1) processes». **Congreso**: 2018 CRoNoS Summer Course and Workshop on Functional Data Analysis (Iasi, Rumanía) 2018. Autores: J. Álvarez-Liébana y M. D. Ruiz-Medina.

* [**Comité organizador**]{.hl-green}: «1st Spanish Young Statisticians and Operational Researchers Meeting» 2017. IEMATH-GR.

* [**Contribución invitada**]{.hl-purple}: «Strong consistency results for the estimation and prediction of ARH(1) processes». **Congreso**: Congreso Bienal de la Real Sociedad Matemática Española (Zaragoza) 2017. Autores: J. Álvarez-Liébana y M. D. Ruiz-Medina.

* [**Comité organizador**]{.hl-green}: «IX Jornadas de R» 2017. Universidad de Granada.

* [**Comité organizador**]{.hl-green}: «I Jornadas de Investigadores en Formación: fomentando la interdisciplinariedad» 2016. Universidad de Granada.

* [**Comité científico**]{.hl-green}: «I Jornadas de Investigadores en Formación: fomentando la interdisciplinariedad» 2016. Universidad de Granada.

