---
title: "Divulgación"
description-meta: "{{< meta website.description >}}"
title-block-banner: "#ffe64acf"
title-block-banner-color: "#000000"
page-layout: full
toc: true
toc-location: right
toc-title: Curso académico
---

## [Newsletter]{.hl-yellow}

Puedes [**suscribirte a mi newsletter**]{.hl-yellow} de manera gratuita en [**Cartas de Laplace**](https://cartasdelaplace.substack.com/)


* [**Newsletter Cartas de Laplace**]{.hl-green}: [«Correlación no implica causalidad…pero sí un Nobel»](https://cartasdelaplace.substack.com/p/carta-4) (20 de octubre de 2021).
* [**Newsletter Cartas de Laplace**]{.hl-green}: [«¿Qué sucedió en Alemania? Dataviz de las elecciones alemanas»](https://cartasdelaplace.substack.com/p/carta-3) (5 de octubre de 2021).
* [**Newsletter Cartas de Laplace**]{.hl-green}: [«La importancia de visualizar datos»](https://cartasdelaplace.substack.com/p/carta-2) (28 de septiembre de 2021).

### [Apariciones en prensa]{.hl-purple}


* [**Noticia en El Confidencial**]{.hl-green}: [«En barrio rico y de derechas: ¿la Lotería de Navidad cae donde más falta hace?»](https://www.elconfidencial.com/loteria-de-navidad/2022-12-17/loteria-navidad-barrio-rico-derechas-cae-mas-falta-hace_3541476/). Artículo de Miguel Ángel Gavilanes, Ana Ruiz y Francisco París para El Confidencial (17 de diciembre de 2022).

* [**Desmentido en maldita.es**]{.hl-red}: [«Por qué los datos no sostienen que España sea el país con más funcionarios de Europa: es el 25º en porcentaje de empleados públicos»](https://maldita.es/malditateexplica/20220923/espana-pais-mas-funcionarios-datos-europa/). Artículo de Maldito Explica para maldita.es (13 de septiembre de 2022).

* [**Noticia en El Confidencial**]{.hl-green}: [«Las matemáticas detrás del fenómeno Wordle para ganar antes que nadie»](https://www.elconfidencial.com/tecnologia/2022-01-13/matematicas-wordle-juego-estadistica_3357239/). Artículo de Mario Escribano para El Confidencial (13 de enero de 2022).

* [**Divulgación en The Conversation**]{.hl-orange}: [«Los matemáticos también jugamos a la lotería»](https://theconversation.com/los-matematicos-tambien-jugamos-a-la-loteria-aunque-no-deberiamos-174108). Artículo para The Conversation y la Unidad de Cultura Científica de la UCM (20 de diciembre de 2021).

* [**Divulgación en Materia (El País)**]{.hl-orange}: [«Cómo el ataque de Pearl Harbor cambió la estadística de las pruebas diagnósticas»](https://elpais.com/ciencia/cafe-y-teoremas/2021-12-07/como-el-ataque-de-pearl-harbor-cambio-la-estadistica-de-las-pruebas-diagnosticas.html). Artículo con Joaquín Minaya para El País (7 de diciembre de 2021).

* [**Desmentido en maldita.es**]{.hl-red}: [«Qué es la paradoja de Simpson y cómo puede hacernos malinterpretar los datos de las vacunas contra la COVID-19»](https://maldita.es/malditateexplica/20211018/paradoja-simpson-malinterpretar-datos-vacunas-covid/). Artículo de Maldito Explica para maldita.es (8 de septiembre de 2021).

* [**Entrevista en El País**]{.hl-green}: [«Ni gatos ni pasteles: el anestesista y el matemático que arrasan en redes porque ayudan a entender la pandemia»](https://elpais.com/espana/madrid/2021-08-09/ni-gatos-ni-pasteles-el-anestesista-y-el-matematico-que-arrasan-en-redes-porque-ayudan-a-entender-la-pandemia.html). Artículo de Isabel Valdés para El País (9 de agosto de 2021).

* [**Noticia en eldiario.es**]{.hl-green}: [«Ehttps://www.eldiario.es/sociedad/cinco-indicadores-permiten-vislumbrar-cautela-final-pandemia-espana_1_7966297.html»](https://www.eldiario.es/sociedad/cinco-indicadores-permiten-vislumbrar-cautela-final-pandemia-espana_1_7966297.html). Artículo de Mónica Zas para eldiario.es (29 de mayo de 2021).

* [**Desmentido en maldita.es**]{.hl-red}: [«¿De dónde sale el dato de un 54% más de riesgo de haber muerto por COVID-19 en Madrid que el promedio de España del que habla Ángel Gabilondo?»](https://maldita.es/malditodato/20210415/madrid-54-riesgo-morir-covid-gabilondo/). Artículo de Maldito Dato para maldita.es (15 de abril de 2021).


* [**Entrevista en El Comercio**]{.hl-green}: [«El nuevo modelo para aplicar cierres busca anticiparse y evitar la saturación hospitalaria»](https://www.elcomercio.es/asturias/nuevo-modelo-aplicar-cierres-anticiparse-evitar-saturacion-hospitalaria-20210121000636-ntvo.html). Artículo de Laura Mayordomo para El Comercio (21 de enero de 2021).

* [**Entrevista en La Voz de Asturias**]{.hl-green}: [«El matemático que secuencia la pandemia en Asturias: 'El que diga cómo será dentro de un mes se está tirando el pisto'»](https://www.lavozdeasturias.es/noticia/asturias/2021/01/20/matematico-secuencia-pandemia-asturias-diga-sera-dentro-mes-tirando-pisto/00031611162707190915383.htm). Artículo de Luís Fernández para La Voz de Asturias (20 de enero de 2021).

* [**Noticia en eldiario.es**]{.hl-green}: [«España triplica en dos meses la cifra de muertos por coronavirus y se aproxima a los 150 diarios»](https://www.eldiario.es/sociedad/espana-aproxima-150-muertos-dia-coronavirus-lejos-todavia-pico-invierno_1_6377111.html). Artículo de Belén Remacha y Raúl Sánchez para eldiario.es (1 de noviembre de 2020).

* [**Noticia en El Confidencial**]{.hl-green}: [«Enganchados al Excel: cómo su (mal) uso está alimentando el caos en los datos del covid»](https://www.elconfidencial.com/tecnologia/2020-10-28/excel-coronavirus-covid-datos-caos-programa_2808600/). Artículo de Guillermo Cid para El Confidencial (28 de octubre de 2020).

* [**Análisis en NIUS**]{.hl-orange}: [«España llega a un millón de contagios oficiales pero la cifra real supera los 3.5 millones»](https://www.niusdiario.es/sociedad/sanidad/millon-casos-coronavirus-espana-pero-cifra-real-tres-millones-y-medio_18_3030570153.html). Análisis propio de la evolución de la pandemia para NIUS (21 de octubre de 2020).

* [**Entrevista en El País**]{.hl-green}: [«James Rhodes se convierte en el amigo invisible de un 'científico precario' madrileño»](https://verne.elpais.com/verne/2019/12/20/articulo/1576858095_240776.html). Entrevista de Hector Llanos para Verne (20 de diciembre de 2019).


* [**Desmentido en maldita.es**]{.hl-red}: [«No, no hay ningún algoritmo secreto que demuestre que haya habido pucherazo electoral en las elecciones generales del 10N»](https://maldita.es/malditobulo/20191120/no-no-hay-ningun-algoritmo-secreto-que-demuestre-que-haya-habido-pucherazo-electoral-en-las-elecciones-generales-del-10n/). Artículo de Maldito Bulo para maldita.es (20 de noviembre de 2019).


### [Apariciones en TV y radio]{.hl-purple}


* [**Entrevista en TVE**]{.hl-green}: entrevista en «La hora de la 1» el 16/10/2020 sobre alertas del covid España vs Europa. [**Link a la entrevista**](https://www.youtube.com/watch?v=LRC2PN2Wido)

* [**Entrevista en RNE**]{.hl-green}: entrevista en «Raíz de 5» el 30/03/2020, en RNE5, sobre los modelos matemáticos aplicados durante la pandemia de covid. [**Link a la entrevista**](https://www.rtve.es/play/audios/raiz-de-5/raiz-5-modelos-matematicos-sobre-coronavirus-javier-alvarez-liebana-30-03-20/5548324/)


### [Twitter, Instagram, Youtube y Twitch]{.hl-purple}



* [**Divulgación en IG**]{.hl-yellow}: publicación sobre las 3M de la estadística, media, moda y mediana. Link: <https://www.instagram.com/p/CQvsOmMFkmA/> (30 de junio de 2021)

* [**Divulgación en IG**]{.hl-yellow}: publicación sobre Sophie Germain. Link: <https://www.instagram.com/p/CO02oxanalP/> (13 de mayo de 2021)

* [**Divulgación en IG**]{.hl-yellow}: publicación sobre los números primos y las cigarras. Link: <https://www.instagram.com/p/CP8JJXKlI2T/> (10 de junio de 2021)

* [**Charla Youtube**]{.hl-red}: charla para EventEx titulada [«Contando taxis, ganando guerras»](https://www.youtube.com/watch?v=1N-gM3m9yUI&t=749s) (12 de diciembre de 2020)

* [**Divulgación en IG**]{.hl-yellow}: publicación sobre la Ley de Benford. Link: < <https://www.instagram.com/p/CHF5SW3lwpl/> (2 de noviembre de 2020)

* [**Divulgación en IG**]{.hl-yellow}: publicación sobre el Sesgo del Superviviente. Link: < <https://www.instagram.com/p/CGz1O7DFP8Q/> (26 de octubre de 2020)

* [**Entrevista en Youtube**]{.hl-red}: entrevista para lasmatematicas.es titulada [«TODAS las MATEMÁTICAS detrás del COVID-19»](https://www.youtube.com/watch?v=0IMB72QmXRs) (2 de septiembre de 2020)

* [**Entrevista en Youtube**]{.hl-red}: entrevista para el canal de Santi García Cremades titulada [«¿Por qué es tan DIFÍCIL PREDECIR MODELOS MATEMÁTICOS en estos días?»](https://www.youtube.com/watch?v=W449qPUsFu8) (31 de marzo de 2020)


### [Seminario/charla]{.hl-purple}

* [**Seminario/charla**]{.hl-green}: «¿Qué hace un matemático como yo en un sitio como este?», organizado por la Universidad de Extremadura. 2022

* [**Seminario/charla**]{.hl-green}: «Mesa redonda: la divulgación en matemáticas», organizado por la RSME (Ciudad Real). 2022

* [**Seminario/charla**]{.hl-green}: «R e COVID», organizado por la asociación Usuarios de Software Libre da Terra de Melide (MeLiSA) (Galicia). 2021

* [**Seminario/charla**]{.hl-green}: «Ciencia de Datos y COVID-19», organizado por DASCI (Andalucía). Ciclo «Ada Lovelace» 2021

* [**Seminario/charla**]{.hl-green}: «Estadística en la guerra, tanto en Pearl Harbor como en el desembarco de Normandía» en el XXII ENEM (Murcia), organizado por la ANEM 2021

* [**Seminario/charla**]{.hl-green}: «A journey through Functional Data Analysis», organizado por el ICMAT (CSIC, Madrid) 2019

* [**Seminario/charla**]{.hl-green}: «Machine Learning: supervised and non supervised learning», organizado por IEMATH-GR (Universidad de Granada) 2016


